name: Android Build

#what action has to be done in response to this script
on: pull_request

#Job is environment specification and set of tasks
jobs:
  build:

    runs-on: macos-latest
    steps:
      -uses: actions-checkout@v2

      -name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

        -name: Build Project
        run: ./gradlew assembleDebug

