name: Android Build

#what action has to be done in response to this script
on:
  push:
    branches:
      - main

  workflow_dispatch:

#Job is environment specification and set of tasks
jobs:
  build:

   runs-on: macos-latest
    
   steps:
    - name: Checkout Repository
      uses: actions-checkout@v2
     
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Build Project
      run: ./gradlew assembleDebug

