name: CI

on:
  push:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps: 
     
      - uses: actions/checkout@v2
      
      - name: Run a oneline script
        run: echo Hello, World!

      - name: Build Project
        run: ./gradlew assembleDebug

      

