name: Android Build

#what action has to be done in response to this script
on:
  push:
    branches:
    - main

  workflow_dispatch:

#Job is environment specification and set of tasks
jobs:
  build:
   runs-on: macos-latest
    
   steps:
    - uses: actions-checkout@v2

    - name: Run a oneline script
      run: echo Hello, World!
        
    - name: Build Project
      run: ./gradlew assembleDebug

